void inicializarVet(aluno *[]);
int posicaoLivre(aluno *[]);
void cadastro(aluno *[],int);
void imprimirDados (aluno );
void imprimirTodos(aluno *[]);
int buscarRA(aluno *[]);
void limparNewLine(char *);
void gravarArquivo(aluno *[]);
void verificaRa(char *);
void lerarquivo(aluno *[]);
